# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43f7da0141d00d409610a8e362b6c189ce0b8b0b7aadfad88dfaf2910fc7944509d5d0d8cfa944a63a9d6f7a2d67f2eee2c0f81b07afb578cc38188823ef5e14

test:
  secret_key_base: 5e315846732a15f57c08fa9c7601add409a5c6ffdd8f22d0d201214d87f5195d7cb04df609c0dfef88581c1f3c6e4f7e66f4b7a68a8ce386bcda263cf12427bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
